# Placeholder config
port_ui = 9080
port_graphql = 9090
port_health = 9091
port_tariff = 8081
port_ontology = 8082
port_advice = 8083
port_notify = 8084
port_ingest = 8085
port_config = 8090
port_billing = 8091
port_scheduler = 8092

fuseki_baseUrl = "http://localhost:3030/lww"
tariff_file = "../data/tariffs.lk.json"
timezone = "Asia/Colombo"

advice_baseUrl = "http://localhost:8083"
tariff_baseUrl = "http://localhost:8081"
ontology_baseUrl = "http://localhost:8082"
# (empty) — services use defaults; keep file for future overrides
